//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthView.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitatePacienti:Interfaces.IDataAccesObjectWithSinglePk
    {
        public System.Guid id { get; set; }
        public Nullable<System.DateTimeOffset> C__createdAt { get; set; }
        public Nullable<System.DateTimeOffset> C__updatedAt { get; set; }
        public byte[] C__version { get; set; }
        public Nullable<bool> C__deleted { get; set; }
        public Nullable<int> Umiditate { get; set; }
        public Nullable<System.DateTimeOffset> Data { get; set; }
        public Nullable<int> SenzorEKG { get; set; }
        public System.Guid IDPacient { get; set; }
        public Nullable<int> Puls { get; set; }
        public string Status { get; set; }
        public Nullable<int> Temperatura { get; set; }
        public Nullable<System.Guid> IDDoctor { get; set; }
        public Nullable<bool> complete { get; set; }
    
        public virtual Pacienti Pacienti { get; set; }
        public virtual Doctori Doctori { get; set; }

        public Guid Id { get; set; }
    }
}
