//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthView.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctori:Interfaces.IDataAccesObjectWithSinglePk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctori()
        {
            this.ActivitatePacienti = new HashSet<ActivitatePacienti>();
            this.Recomandari = new HashSet<Recomandari>();
            this.Pacienti = new HashSet<Pacienti>();
        }
    
        public string NumeDoctor { get; set; }
        public string PrenumeDoctor { get; set; }
        public string Functie { get; set; }
        public string Spital { get; set; }
        public string Status { get; set; }
        public System.Guid Id { get; set; }
        public string AspNetUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitatePacienti> ActivitatePacienti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomandari> Recomandari { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pacienti> Pacienti { get; set; }
    }
}
