//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HealthView.Models.Interfaces;

namespace HealthView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recomandari:Interfaces.IModel, IModelWithSinglePK
    {
        public System.Guid ID { get; set; }
        public System.Guid IDPacient { get; set; }
        public string TipRecomandare { get; set; }
        public Nullable<decimal> Durata { get; set; }
        public string AlteIndicatii { get; set; }
        public System.Guid IDDoctor { get; set; }
    
        public virtual Doctori Doctori { get; set; }
        public virtual Pacienti Pacienti { get; set; }
        public Guid Id { get; set; }
    }
}
